In [2]:

import tensorflow as tf
with tf.Session() as sess:  
    inputs = [[1],[2],[3]]
    padding = [[2,3],[1,2]]
    print(sess.run(tf.pad(inputs,padding)))




[[0 0 0 0]
 [0 0 0 0]
 [0 1 0 0]
 [0 2 0 0]
 [0 3 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
